"""
blocks/output/unifiers/pptx_unifier.py — PowerPoint export unifier block.

Accepts text (split by H1/H2 headings into slides) + PNG images from upstream,
produces a downloadable .pptx via python-pptx.
"""
from __future__ import annotations

import re
from io import BytesIO

from blocks.base import BlockData, BlockDescription, IBlock
from blocks.registry import register_block


@register_block
class PPTXUnifierBlock(IBlock):
    description = BlockDescription(
        name="pptx_unifier",
        display_name="Export as PowerPoint",
        group="output",
        input_types=["text", "binary/png"],
        output_types=["binary/pptx"],
        parameters=[
            {
                "name": "theme_color",
                "type": "color",
                "default": "#2D4A8A",
                "label": "Accent colour (hex)",
            },
            {
                "name": "font",
                "type": "select",
                "options": ["Calibri", "Arial", "OpenDyslexic"],
                "default": "Calibri",
            },
            {
                "name": "layout",
                "type": "select",
                "options": ["title_content", "image_right", "full_image"],
                "default": "title_content",
            },
        ],
    )

    async def execute(self, inputs: list[BlockData], params: dict) -> list[BlockData]:
        try:
            from pptx import Presentation  # type: ignore
            from pptx.util import Inches, Pt
            from pptx.dml.color import RGBColor
        except ImportError:
            return [BlockData(
                text="[PPTX export unavailable — python-pptx not installed]",
                mime_type="text/plain",
            )]

        color_hex = params.get("theme_color", "#2D4A8A").lstrip("#")
        accent = RGBColor(
            int(color_hex[0:2], 16),
            int(color_hex[2:4], 16),
            int(color_hex[4:6], 16),
        )
        font_name = params.get("font", "Calibri")

        text_blocks = [bd.text for bd in inputs if bd.text]
        png_blocks = [bd.binary for bd in inputs if bd.mime_type == "image/png" and bd.binary]

        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        combined = "\n\n".join(text_blocks)
        # Split on H1 / H2 markdown headings
        sections = re.split(r"^#{1,2} (.+)$", combined, flags=re.MULTILINE)

        # Title slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = (sections[0].strip()[:80] or "DysLearnia Export")
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = "Generated by DysLearnia"

        # Content slides
        for i in range(1, len(sections), 2):
            heading = sections[i] if i < len(sections) else ""
            body = sections[i + 1].strip() if i + 1 < len(sections) else ""
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = heading[:80]
            tf = slide.placeholders[1].text_frame
            tf.text = ""
            for line in body.split("\n"):
                line = line.strip().lstrip("- •").strip()
                if not line:
                    continue
                p = tf.add_paragraph()
                p.text = line
                p.font.size = Pt(16)
                p.font.name = font_name

        # Infographic slides (full-bleed PNG)
        for png_bytes in png_blocks:
            slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
            with BytesIO(png_bytes) as img_io:
                slide.shapes.add_picture(
                    img_io,
                    Inches(0),
                    Inches(0),
                    width=prs.slide_width,
                    height=prs.slide_height,
                )

        out = BytesIO()
        prs.save(out)

        return [BlockData(
            binary=out.getvalue(),
            mime_type=(
                "application/vnd.openxmlformats-officedocument"
                ".presentationml.presentation"
            ),
            metadata={"filename": "dyslearnia_export.pptx"},
        )]
