"""
blocks/transform/infographic.py — Infographic block.

Renders course text as a visually styled PNG infographic using Pillow.
No LLM required; the text is formatted as a titled card with body copy.
"""
from __future__ import annotations

from blocks.base import BlockData, BlockDescription, IBlock
from blocks.registry import register_block

_THEMES = {
    "clean": {"bg": (255, 255, 255), "header": (45, 74, 138), "text": (33, 33, 33)},
    "dyslexia": {"bg": (255, 253, 231), "header": (74, 20, 140), "text": (33, 33, 33)},
    "dark": {"bg": (30, 30, 30), "header": (100, 181, 246), "text": (238, 238, 238)},
}


@register_block
class InfographicBlock(IBlock):
    description = BlockDescription(
        name="infographic",
        display_name="Infographic",
        group="transform",
        input_types=["text"],
        output_types=["binary/png"],
        parameters=[
            {
                "name": "theme",
                "type": "select",
                "options": ["clean", "dyslexia", "dark"],
                "default": "clean",
            },
            {
                "name": "columns",
                "type": "select",
                "options": ["1", "2"],
                "default": "1",
                "label": "Layout columns",
            },
            {
                "name": "title",
                "type": "text",
                "default": "DysLearnia Summary",
                "label": "Card title",
            },
        ],
    )

    async def execute(self, inputs: list[BlockData], params: dict) -> list[BlockData]:
        try:
            from PIL import Image, ImageDraw, ImageFont
        except ImportError:
            return [BlockData(
                text="[Infographic unavailable — Pillow not installed]",
                mime_type="text/plain",
                metadata={"error": "Pillow not installed"},
            )]

        import io
        import textwrap

        text = self.first_text(inputs)
        if not text:
            return [BlockData(text="", metadata={"error": "No text input"})]

        theme_name = params.get("theme", "clean")
        theme = _THEMES.get(theme_name, _THEMES["clean"])
        title = params.get("title", "DysLearnia Summary")

        # Canvas dimensions
        width, height = 1200, 800
        img = Image.new("RGB", (width, height), theme["bg"])
        draw = ImageDraw.Draw(img)

        # Try to load a font; fall back to default
        try:
            title_font = ImageFont.truetype("arial.ttf", 36)
            body_font = ImageFont.truetype("arial.ttf", 20)
        except Exception:
            title_font = ImageFont.load_default()
            body_font = ImageFont.load_default()

        # Header bar
        draw.rectangle([0, 0, width, 80], fill=theme["header"])
        draw.text((30, 20), title, font=title_font, fill=(255, 255, 255))

        # Body text — wrap at 90 chars
        wrapped = textwrap.wrap(text[:2000], width=90)
        y = 100
        for line in wrapped:
            if y > height - 40:
                break
            draw.text((30, y), line, font=body_font, fill=theme["text"])
            y += 28

        # Footer
        draw.rectangle([0, height - 30, width, height], fill=theme["header"])
        draw.text((30, height - 22), "Generated by DysLearnia", font=body_font,
                  fill=(255, 255, 255))

        buf = io.BytesIO()
        img.save(buf, format="PNG")
        png_bytes = buf.getvalue()

        return [BlockData(
            binary=png_bytes,
            mime_type="image/png",
            metadata={
                "width": width,
                "height": height,
                "theme": theme_name,
            },
        )]
